services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_MPK: ${MYSQL_DATABASE_MPK}
      MYSQL_DATABASE_OPEN: ${MYSQL_DATABASE_OPEN}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    environment:
      PORT: 8000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME_MPK: ${MYSQL_DATABASE_MPK}
      DB_NAME_OPEN: ${MYSQL_DATABASE_OPEN}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: mpkbet-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: bun run start --host
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    # env_file:
    #   - .env
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:
    external: true

networks:
  app-network:
